CREATE TABLE accounts (
                          id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username  VARCHAR(32) NOT NULL UNIQUE,
                          password  VARCHAR(255) NOT NULL,
                          create_at TIMESTAMP(6));

CREATE TABLE ic_ots (
                        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title_printing VARCHAR(32) NOT NULL,
                        shaft_size     INTEGER      NOT NULL,
                        author_id      BIGINT CONSTRAINT fkcv0pogpi9nie9oj1pdtxhtiwl references accounts,
                        create_at      TIMESTAMP(6));
CREATE INDEX ic_ots__author_id__fkey ON ic_ots(author_id);
CREATE INDEX ic_ots__title_printing__idx ON ic_ots(title_printing);

CREATE TABLE forms_ic_ots (
                              id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              title_form       VARCHAR(32),
                              interval_labels  INTEGER,
                              quantity_imprint INTEGER,
                              right_margin     INTEGER,
                              width            INTEGER NOT NULL,
                              owner_id         BIGINT CONSTRAINT fk90w4xypduklmga4on1dto7fqj references ic_ots);
CREATE INDEX forms_ic_ots__owner_id__fkey ON forms_ic_ots(owner_id);
CREATE INDEX forms_ic_ots__title_form__idx ON forms_ic_ots(title_form);

CREATE TABLE ots (
                     id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title_printing VARCHAR(32) NOT NULL,
                     shaft_size     INTEGER      NOT NULL,
                     author_id      BIGINT CONSTRAINT fkj4ohtlnh9867laronhoinjn9d references accounts,
                     create_at      TIMESTAMP(6));
CREATE INDEX ots__author_id__fkey ON ots(author_id);
CREATE INDEX ots__title_printing__idx ON ots(title_printing);

CREATE TABLE forms_ots (
                           id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           title_form           VARCHAR(32),
                           indentation_on_shaft INTEGER,
                           interval_labels      INTEGER,
                           number_on_shaft      INTEGER,
                           tooth_on_shaft       INTEGER,
                           owner_id             BIGINT CONSTRAINT fkia05366mgfqm007f6pxb6q240 references ots);
CREATE INDEX forms_ots__owner_id__fkey ON forms_ots(owner_id);
CREATE INDEX forms_ots__title_form__idx ON forms_ots(title_form);